apiVersion: v1
kind: Service
metadata:
  name: delivery-load-balancer
  labels:
    app: delivery-load-balancer
  namespace: mantogin-hw8
spec:
  selector:
    app: hw8-delivery-app
  ports:
    - protocol: TCP
      name: metrics
      port: 8002
      targetPort: 8002
  type: LoadBalancer